# Generated by Django 3.2.7 on 2021-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idmodulo', models.AutoField(db_column='IdModulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('capacidad', models.IntegerField(db_column='Capacidad')),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
    ]
