# Generated by Django 3.2.7 on 2021-10-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'managed': False, 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
    ]
