# Generated by Django 3.2.7 on 2021-10-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idasistencia', models.AutoField(db_column='IdAsistencia', primary_key=True, serialize=False)),
                ('entrada', models.TimeField(db_column='Entrada', verbose_name='Entrada')),
                ('salida', models.TimeField(db_column='Salida', verbose_name='Salida')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
    ]
