# Generated by Django 3.2.7 on 2021-09-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.IntegerField()),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
            ],
            options={
                'verbose_name': 'bitacora',
                'verbose_name_plural': 'bitacoras',
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
    ]
