# Generated by Django 3.2.7 on 2021-09-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_voluntariolocal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.IntegerField()),
                ('creencias_religiosas', models.CharField(max_length=50)),
                ('horas_acumuladas', models.IntegerField()),
                ('dia_de_voluntariado', models.IntegerField()),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'voluntario',
                'verbose_name_plural': 'voluntarios',
                'db_table': 'voluntario',
                'managed': False,
            },
        ),
    ]
