# Generated by Django 3.2.7 on 2021-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.AutoField(db_column='IdPais', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
    ]
