# Generated by Django 3.2.7 on 2021-10-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': False, 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
