# Generated by Django 3.2.7 on 2021-09-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movilidad',
            fields=[
                ('id_movilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.IntegerField()),
                ('plan_movilidad', models.CharField(max_length=500)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('habitacion', models.CharField(max_length=3)),
                ('locker', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'movilidad',
                'verbose_name_plural': 'movilidades',
                'db_table': 'movilidad',
                'managed': False,
            },
        ),
    ]
