# Generated by Django 3.2.7 on 2021-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creencias',
            fields=[
                ('idcreencia', models.AutoField(db_column='IdCreencia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
            ],
            options={
                'db_table': 'creencias',
                'managed': False,
            },
        ),
    ]
