# Generated by Django 3.2.7 on 2021-10-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creencias',
            options={'managed': False, 'verbose_name': 'Creencia Religiosa', 'verbose_name_plural': 'Creencias Religiosas'},
        ),
    ]
