# Generated by Django 3.2.7 on 2021-09-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('foto', models.CharField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.IntegerField()),
                ('rol', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
