# Generated by Django 3.2.7 on 2021-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diasdevoluntariado',
            fields=[
                ('iddia', models.AutoField(db_column='IdDia', primary_key=True, serialize=False)),
                ('diaarealizar', models.DateField(db_column='DiaARealizar')),
                ('fkidvoluntario', models.IntegerField(db_column='FkIdVoluntario')),
                ('fkidusuario', models.IntegerField(db_column='FkIdUsuario')),
            ],
            options={
                'db_table': 'diasdevoluntariado',
                'managed': False,
            },
        ),
    ]
