# Generated by Django 3.2.7 on 2021-10-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diasdevoluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasdevoluntariado',
            options={'managed': False, 'verbose_name': 'Día de Voluntariado', 'verbose_name_plural': 'Días de Voluntariado'},
        ),
    ]
