# Generated by Django 3.2.7 on 2021-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horasdevoluntariado',
            fields=[
                ('idhoras', models.AutoField(db_column='IdHoras', primary_key=True, serialize=False)),
                ('fkidpersona', models.IntegerField(db_column='FKIdPersona')),
                ('fkidusuario', models.IntegerField(db_column='FKIdUsuario')),
                ('dia', models.DateField(db_column='Dia')),
                ('horasrealizadas', models.IntegerField(db_column='HorasRealizadas')),
            ],
            options={
                'db_table': 'horasdevoluntariado',
                'managed': False,
            },
        ),
    ]
