# Generated by Django 3.2.7 on 2021-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('idvoluntario', models.AutoField(db_column='IdVoluntario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('telefono', models.CharField(db_column='Telefono', max_length=16)),
                ('genero', models.CharField(db_column='Genero', max_length=1)),
                ('edad', models.IntegerField(db_column='Edad')),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento')),
                ('nacionalidad', models.CharField(db_column='Nacionalidad', max_length=50)),
                ('fkidusuario', models.IntegerField(db_column='FKIdUsuario')),
                ('correo', models.CharField(db_column='Correo', max_length=75)),
                ('direccion', models.CharField(db_column='Direccion', max_length=120)),
                ('tipovoluntario', models.CharField(db_column='TipoVoluntario', max_length=20)),
            ],
            options={
                'db_table': 'voluntario',
                'managed': False,
            },
        ),
    ]
