# Generated by Django 3.2.7 on 2021-10-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caravanamigrante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caravanamigrante',
            options={'managed': False, 'verbose_name': 'Caravana Migrante', 'verbose_name_plural': 'Caravana Migrantes'},
        ),
    ]
