# Generated by Django 3.2.7 on 2021-10-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidamigrante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salidamigrante',
            options={'managed': False, 'verbose_name': 'Salida de Migrante', 'verbose_name_plural': 'Salidas de Migrante'},
        ),
    ]
