# Generated by Django 3.2.7 on 2021-10-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('iddonacion', models.AutoField(db_column='IdDonacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200)),
                ('telefono', models.CharField(db_column='Telefono', max_length=18)),
                ('direccion', models.CharField(db_column='Direccion', max_length=254)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=254)),
                ('fechadeentrega', models.DateTimeField(db_column='FechaDeEntrega')),
                ('fkidusuario', models.IntegerField(db_column='FKIdUsuario')),
            ],
            options={
                'db_table': 'donacion',
                'managed': False,
            },
        ),
    ]
