<<<<<<< HEAD:migrante/donacion/migrations/0001_initial.py
# Generated by Django 3.2.7 on 2021-09-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=254)),
                ('lugar', models.CharField(max_length=120)),
                ('tipo_donacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'donacion',
                'verbose_name_plural': 'donaciones',
                'db_table': 'donacion',
                'managed': False,
            },
        ),
    ]
=======
# Generated by Django 3.2.7 on 2021-10-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('iddonacion', models.AutoField(db_column='IdDonacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200)),
                ('telefono', models.CharField(db_column='Telefono', max_length=18)),
                ('direccion', models.CharField(db_column='Direccion', max_length=254)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=254)),
                ('fechadeentrega', models.DateTimeField(db_column='FechaDeEntrega')),
                ('fkidusuario', models.IntegerField(db_column='FKIdUsuario')),
            ],
            options={
                'db_table': 'donacion',
                'managed': False,
            },
        ),
    ]
>>>>>>> Jose:Proyecto/donacion/migrations/0001_initial.py
