# Generated by Django 3.2.7 on 2021-10-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donacion',
            options={'managed': False, 'verbose_name': 'Donación', 'verbose_name_plural': 'Donaciones'},
        ),
    ]
