# Generated by Django 3.2.7 on 2021-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodonacion',
            fields=[
                ('idtipodonacion', models.AutoField(db_column='IdTipoDonacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=75)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
            ],
            options={
                'db_table': 'tipodonacion',
                'managed': False,
            },
        ),
    ]
