# Generated by Django 3.2.7 on 2021-10-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipodonacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodonacion',
            options={'managed': False, 'verbose_name': 'Tipo de Donación', 'verbose_name_plural': 'Tipo de Donaciones'},
        ),
    ]
