# Generated by Django 3.2.7 on 2021-10-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'managed': False, 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
    ]
