# Generated by Django 3.2.7 on 2021-10-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradamigrante',
            fields=[
                ('idmovilidad', models.AutoField(db_column='IdMovilidad', primary_key=True, serialize=False)),
                ('fechaentrada', models.DateTimeField(db_column='FechaEntrada')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=254)),
            ],
            options={
                'db_table': 'entradamigrante',
                'managed': False,
            },
        ),
    ]
