# Generated by Django 3.2.7 on 2021-10-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradamigrante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradamigrante',
            options={'managed': False, 'verbose_name': 'Entrada Migrante', 'verbose_name_plural': 'Entrada Migrantes'},
        ),
    ]
